language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository/io/runtime

before_install:  
  - chmod +x mvnw

before_script:
  - psql -c 'create database brj;' -U postgres

services:
  - postgresql